version: "3.7"

services:
  django_web:
    # image:smartmammo:2.1.0
    build: .
    command: >
      
      bash -c "python3 -m pip install --upgrade pip &&\
       pip install gunicorn &&\
       python3 manage.py migrate &&\
       gunicorn mlAmeri.wsgi:application --bind 0.0.0.0:8000 --timeout 10000"
    volumes:
     # - type: volume
      - "static:/app/staitc"
      - "media:/app/media"
      - ".:/app"

    ports:
      - 8000:8000

    restart: always


volumes:
  static:
  media:

