# Generated by Django 3.2.9 on 2021-12-02 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.log')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True, help_text='what is your image', null=True)),
                ('variable_1', models.SmallIntegerField()),
                ('method', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('app.log',),
        ),
        migrations.CreateModel(
            name='ModelResult',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.log')),
                ('result', models.ImageField(upload_to='')),
                ('client_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.clientrequest')),
            ],
            bases=('app.log',),
        ),
    ]
